"""empty message

Revision ID: 062d38803e7d
Revises: 
Create Date: 2024-09-26 18:55:03.013048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '062d38803e7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_quiz', ['user_id', 'quiz_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_quiz', type_='unique')

    # ### end Alembic commands ###
