"""Allow multiple score entries per user and quiz

Revision ID: f5d6fce8e42c
Revises: 062d38803e7d
Create Date: 2024-10-12 18:40:13.452165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5d6fce8e42c'
down_revision = '062d38803e7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_quiz', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_quiz', ['user_id', 'quiz_id'])

    # ### end Alembic commands ###
